### ISSUE TITLE
[REQ] fix license on GH

### ISSUE THREAD

**Issue by MarcoRavich** [NIXXAMPS/AmpModellingLib#1]
Hi there, 1st of all thanks for your awesome (voluntary) work !

Since we've doxed this git in our [HyMPS project](https://github.com/forart/HyMPS) (under [Effects](https://github.com/forart/HyMPS/blob/main/AudioFXs.md#audio---effects-) - [Guitar](https://github.com/forart/HyMPS/blob/main/Guitar.md#audio---effects---guitar-) - [Libraries](https://github.com/forart/HyMPS/blob/main/Guitar.md#libraries-) section), can you please fix licensing terms for it ?

Our "problem" is that the relative license badge isn't generated correctly:

![](https://flat.badgen.net/github/license/nkauzljar/AmpModellingLib)
(generator URL: https://flat.badgen.net/github/license/nkauzljar/AmpModellingLib)

This could be easily fixed by choosing a "correct" license file through the GH's wizard.

Although it may sounds like a minor aspect, this may help other devs to understand how reuse your code in other open projects and vice-versa that's a determining factor for the success and longevity of your project.

Last but not least, let us know how - in your opinion - we could improve our categorizations and links to resources in order to favor collaboration between developers (and therefore evolution) of listed projects.

Thanks in advance.

**Comment by nkauzljar** [comment]
Hi,
I added the license to the project.
Cheers
